# Generated by Django 4.1.3 on 2022-11-26 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
