# Generated by Django 4.1.3 on 2022-11-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_alter_entry_context_alter_entry_synonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='context',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='synonym',
            field=models.TextField(default=''),
        ),
    ]
